# Generated by Django 5.2.7 on 2025-12-22 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0001_initial'),
        ('mahasiswa', '0006_remove_matakuliah_dosen_mk_remove_matakuliah_mhs_mk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=100)),
                ('kode_mk', models.CharField(max_length=20, unique=True)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('dosen_mk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matakuliah_set', to='dosen.dosen')),
                ('mhs_mk', models.ManyToManyField(blank=True, related_name='matakuliah_set', to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
