# Generated by Django 5.2.7 on 2025-11-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
