# Generated by Django 5.2.7 on 2025-12-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_no_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
