# Generated by Django 5.2.7 on 2025-12-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_mahasiswa_alamat_mahasiswa_jurusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('Teknologi Informasi', 'Teknologi Informasi'), ('Sains Data', 'Sains Data')], max_length=100),
        ),
    ]
