# Generated by Django 5.2.7 on 2025-12-22 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_alter_mahasiswa_jurusan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('homebase', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=100)),
                ('kode_mk', models.CharField(max_length=20, unique=True)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('dosen_mk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matakuliah_set', to='mahasiswa.dosen')),
                ('mhs_mk', models.ManyToManyField(blank=True, related_name='matakuliah_set', to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
