# Generated by Django 5.2.7 on 2025-12-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0005_dosen_matakuliah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='dosen_mk',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='mhs_mk',
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
        migrations.DeleteModel(
            name='MataKuliah',
        ),
    ]
