# Generated by Django 5.2.7 on 2025-12-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('homebase', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
